###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
###############################################################

name: Build Package openWRT/immotalWRT

on:
  workflow_dispatch:

env:
  DL_SDK_SH: scripts/openwrt/dl_sdk-2.sh
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential ccache clang flex bison g++ gawk \
        gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
        python3-distutils python3-setuptools python2.7 rsync swig unzip zlib1g-dev file wget
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Download SDK
      run: |
        mkdir -p openwrt
        cp $DL_SDK_SH openwrt/dl_sdk-2.sh
        cd openwrt
        sh dl_sdk-2.sh

    - name: Update feeds
      run: |
        cd openwrt/sdk
        ./scripts/feeds update -a

    - name: Update new packages
      run: |
        cd openwrt/sdk/feeds/packages/net/
        #rm -rf ddns-scripts/
        rm -rf https-dns-proxy/
        #rm -rf udpxy/
        #git clone https://github.com/sieucaocao/ddns-scripts.git
        git clone https://github.com/sieucaocao/https-dns-proxy.git
        #git clone https://github.com/sieucaocao/udpxy.git
        

    - name: Install feeds
      run: |
        cd openwrt/sdk
        #./scripts/feeds install ddns-scripts
        ./scripts/feeds install https-dns-proxy
        #./scripts/feeds install udpxy

    - name: Fix config file
      run: |
        mkdir -p openwrt/sdk/staging_dir/host/
        touch openwrt/sdk/staging_dir/host/.prereq-build

    - name: Generate default configuration
      run: |
        cd openwrt/sdk
        make defconfig

    - name: Download packages
      run: |
        cd openwrt/sdk
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
         
    - name: Compile package
      id: compile
      run: |
        cd openwrt/sdk
        #make package/ddns-scripts/compile V=s -j$(nproc)
        make package/https-dns-proxy/compile V=s -j$(nproc)
        #make package/udpxy/compile V=s -j$(nproc)
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upload package directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success'
      with:
        name: openwrt_package_r${{ env.DATE }}
        path: openwrt/sdk/bin/packages
