###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
###############################################################

name: Build Image OpenWrt

on:
  workflow_dispatch:

env:
  DEVICE_NAME: mc-mac1200r
  BUILD_SCRIPT: configs/openwrt/imagebuilder/mc-mac1200r-2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE_DIR: true
  DL_IMAGEBUILDER_SH: scripts/openwrt/dl_imagebuilder-2.sh
  CUSTOM_SH: scripts/openwrt/99_custom.sh
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential libncurses-dev zlib1g-dev gcc g++ gawk git \
        gettext libssl-dev xsltproc rsync wget unzip python2.7 python3 python3-distutils
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Download Image Builder
      run: |
        mkdir -p openwrt
        cp $DL_IMAGEBUILDER_SH openwrt/dl_imagebuilder.sh
        cd openwrt
        sh dl_imagebuilder.sh

    - name: Load build script
      run: |
        cp $BUILD_SCRIPT openwrt/imagebuilder/make.sh

    - name: Load custom script
      run: |
        mkdir -p openwrt/imagebuilder/files/etc/uci-defaults
        cp -r $CUSTOM_SH openwrt/imagebuilder/files/etc/uci-defaults

    - name: Skip check gcc/g++
      run: |
        mkdir -p openwrt/imagebuilder/staging_dir/host
        touch openwrt/imagebuilder/staging_dir/host/.prereq-build
        
    - name: Compile firmware
      id: compile
      run: |
        cd openwrt/imagebuilder
        sh make.sh
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: ${{ env.DEVICE_NAME }}_openwrt_bin_${{ env.DATE }}
        path: openwrt/imagebuilder/bin

    - name: Prepare files
      id: prepare
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE_DIR == 'true'
      run: |
        cd openwrt/imagebuilder/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.prepare.outputs.status == 'success' && env.UPLOAD_FIRMWARE_DIR == 'true'
      with:
        name: ${{ env.DEVICE_NAME }}_openwrt_r${{ env.DATE }}
        path: ${{ env.FIRMWARE }}
        
