name: Build OpenWrt Firmware 

on:
  workflow_dispatch:
  
env:
  CUSTOMIZE_SH: scripts/openwrt/99-enable-wifi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3 wget unzip

    - name: Download OpenWrt ImageBuilder
      run: |
        wget https://downloads.openwrt.org/releases/19.07.10/targets/ar71xx/generic/openwrt-imagebuilder-19.07.10-ar71xx-generic.Linux-x86_64.tar.xz
        tar -xf openwrt-imagebuilder-19.07.10-ar71xx-generic.Linux-x86_64.tar.xz
        mv openwrt-imagebuilder-19.07.10-ar71xx-generic.Linux-x86_64 imagebuilder

    - name: Copy Custom Files
      run: |
        cp -r $CUSTOMIZE_SH imagebuilder/99-enable-wifi

    - name: Build OpenWrt Firmware
      run: |
        cd imagebuilder
        make image PROFILE=mc-mac1200r FILES="$CUSTOMIZE_SH" PACKAGES="base-files libc libgcc busybox dropbear mtd uci opkg netifd fstools uclient-fetch logd urandom-seed urngd kmod-gpio-button-hotplug swconfig kmod-ath9k uboot-envtools wpad-basic -dnsmasq dnsmasq-full iptables ip6tables ppp ppp-mod-pppoe firewall odhcpd-ipv6only odhcp6c kmod-ipt-offload -kmod-ath10k-ct kmod-ath10k -ath10k-firmware-qca988x-ct ath10k-firmware-qca988x luci"
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: OpenWrt-Firmware
        path: imagebuilder/bin/targets/ath79/generic/
