###############################################################
# Author(s): Việt Anh Bùi | https://github.com/vietanhbui2000 #
###############################################################

name: Build Package openWRT/immotalWRT

on:
  workflow_dispatch:

env:
  DL_SDK_SH: scripts/openwrt/dl_sdk.sh
  TZ: Asia/Ho_Chi_Minh

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential libncurses-dev zlib1g-dev gawk git \
        gettext libssl-dev xsltproc rsync wget unzip python2.7 python3 python3-distutils
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Download SDK
      run: |
        mkdir -p openwrt
        cp $DL_SDK_SH openwrt/dl_sdk.sh
        cd openwrt
        sh dl_sdk.sh

    - name: Clone package
      run: |
        cd openwrt/sdk/package
        git clone https://github.com/stangri/https-dns-proxy.git
        git checkout 2cf67e3

    - name: Update & install feeds
      run: |
        cd openwrt/sdk
        ./scripts/feeds update -a
        ./scripts/feeds install https-dns-proxy

    - name: Generate default configuration
      run: |
        cd openwrt/sdk
        make defconfig

    - name: Download packages
      run: |
        cd openwrt/sdk
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile package
      id: compile
      run: |
        cd openwrt/sdk
        make package/https-dns-proxy/compile V=s -j$(nproc)
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upload package directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success'
      with:
        name: openwrt_package_r${{ env.DATE }}
        path: openwrt/sdk/bin/packages
